STOCK_LIST = {
    "AAPL": "Apple Inc.", 
    "GOOGL": "Alphabet Inc.", 
    "AMZN": "Amazon.com Inc.", 
    "MSFT": "Microsoft Corporation", 
    "META": "Meta Inc.", 
    "TSLA": "Tesla Inc.", 
    "JPM": "JPMorgan Chase & Co.", 
    "V": "Visa Inc.", 
    "JNJ": "Johnson & Johnson", 
    "BAC": "Bank of America Corp.", 
    "WMT": "Walmart Inc.", 
    "PG": "Procter & Gamble Co.", 
    "MA": "Mastercard Incorporated", 
    "UNH": "UnitedHealth Group Incorporated", 
    "HD": "The Home Depot Inc.",
    "DNUT": "Krispy Kreme Inc.",
    "ADI" : "Analog Devices, Inc.", 
    "AMAT" : "Applied Materials Inc.", 
    "T" : "AT&T Inc.", 
    "ADSK" : "Autodesk Inc.", 
    "BAX" : "Baxter International Inc", 
    "CBOE": "Cboe Global Markets Inc", 
    "C": "Citigroup Inc", 
    "DHR": "Danaher Corp", 
    "DIS": "The Walt Disney Co", 
    "DOW": "Dow Inc", 
    "ECL": "Ecolab Inc", 
    "EQR": "Equity Residential", 
    "EVRG": "Evergy Inc", 
    "EQR": "Equity Residential", 
    "EXC": "Exelon Corp", 
    "FISV": "Fiserv Inc", 
    "GIS": "General Mills Inc", 
    "HON": "Honeywell International Inc.", 
    "HPE": "Hewlett Packard Enterprise Co.", 
    "HUM": "Humana Inc.", 
    "INTU": "Intuit Inc.", 
    "LHX": "L3Harris Technologies Inc.", 
    "MAR": "Marriott International Inc.", 
    "MCD": "McDonald's Corp.", 
    "MRK": "Merck & Co., Inc.", 
    "SOFI": "SoFi Technologies Inc.", 
    "MCO": "Moody's Corp.", 
    "MOS": "The Mosaic Co.", 
    "MTB": "M&T Bank Corp.",
    "SPGI": "S&P Global Inc.", 
    "SYF": "Synchrony Financial", 
    "TROW": "T. Rowe Price Group Inc.", 
    "TFC": "Truist Financial Corp", 
    "VZ": "Verizon Communications Inc." 
}

SP_500 = "^GSPC"